const phieuNhapData = [
    {
        maPhieu: "PN001",
        ngayNhap: "01/10/2024",
        nguoiNhap: "Nguyễn Văn A",
        nhaCungCap: "Công ty ABC",
        trangThai: "Đã hoàn thành",
        tongTien: "500,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bút bi Thiên Long",
                soLuong: 100,
                giaNhap: 3000,
                thanhTien: 300000,
            },
            {
                tenHangHoa: "Sổ tay A5",
                soLuong: 50,
                giaNhap: 4000,
                thanhTien: 200000,
            },
        ],
    },
    {
        maPhieu: "PN002",
        ngayNhap: "02/10/2024",
        nguoiNhap: "Trần Thị B",
        nhaCungCap: "Công ty XYZ",
        trangThai: "Đang xử lý",
        tongTien: "300,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bút dạ quang",
                soLuong: 60,
                giaNhap: 5000,
                thanhTien: 300000,
            },
        ],
    },
    {
        maPhieu: "PN003",
        ngayNhap: "03/10/2024",
        nguoiNhap: "Lê Văn C",
        nhaCungCap: "Công ty DEF",
        trangThai: "Đã hoàn thành",
        tongTien: "700,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Giấy in A4",
                soLuong: 30,
                giaNhap: 7000,
                thanhTien: 210000,
            },
            {
                tenHangHoa: "Kẹp giấy",
                soLuong: 20,
                giaNhap: 5000,
                thanhTien: 100000,
            },
            {
                tenHangHoa: "Bìa còng",
                soLuong: 10,
                giaNhap: 40000,
                thanhTien: 400000,
            },
        ],
    },
    {
        maPhieu: "PN004",
        ngayNhap: "04/10/2024",
        nguoiNhap: "Nguyễn Thị D",
        nhaCungCap: "Công ty GHI",
        trangThai: "Đang xử lý",
        tongTien: "600,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Tập vở 200 trang",
                soLuong: 100,
                giaNhap: 6000,
                thanhTien: 600000,
            },
        ],
    },
    {
        maPhieu: "PN005",
        ngayNhap: "05/10/2024",
        nguoiNhap: "Phạm Văn E",
        nhaCungCap: "Công ty JKL",
        trangThai: "Đã hoàn thành",
        tongTien: "1,200,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Máy in",
                soLuong: 2,
                giaNhap: 600000,
                thanhTien: 1200000,
            },
        ],
    },
    {
        maPhieu: "PN006",
        ngayNhap: "06/10/2024",
        nguoiNhap: "Nguyễn Văn F",
        nhaCungCap: "Công ty MNO",
        trangThai: "Đang xử lý",
        tongTien: "900,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Máy tính xách tay",
                soLuong: 1,
                giaNhap: 900000,
                thanhTien: 900000,
            },
        ],
    },
    {
        maPhieu: "PN007",
        ngayNhap: "07/10/2024",
        nguoiNhap: "Lê Thị G",
        nhaCungCap: "Công ty PQR",
        trangThai: "Đã hoàn thành",
        tongTien: "1,000,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bảng viết",
                soLuong: 5,
                giaNhap: 200000,
                thanhTien: 1000000,
            },
        ],
    },
    {
        maPhieu: "PN008",
        ngayNhap: "08/10/2024",
        nguoiNhap: "Trần Văn H",
        nhaCungCap: "Công ty STU",
        trangThai: "Đang xử lý",
        tongTien: "750,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Máy chiếu",
                soLuong: 1,
                giaNhap: 750000,
                thanhTien: 750000,
            },
        ],
    },
    {
        maPhieu: "PN009",
        ngayNhap: "09/10/2024",
        nguoiNhap: "Phạm Thị I",
        nhaCungCap: "Công ty VWX",
        trangThai: "Đã hoàn thành",
        tongTien: "300,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Thước kẻ 30cm",
                soLuong: 100,
                giaNhap: 3000,
                thanhTien: 300000,
            },
        ],
    },
    {
        maPhieu: "PN010",
        ngayNhap: "10/10/2024",
        nguoiNhap: "Nguyễn Văn J",
        nhaCungCap: "Công ty YZA",
        trangThai: "Đang xử lý",
        tongTien: "600,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bút lông bảng",
                soLuong: 100,
                giaNhap: 6000,
                thanhTien: 600000,
            },
        ],
    },
    // Thêm dữ liệu tương tự cho các mã phiếu từ PN011 đến PN030
    {
        maPhieu: "PN011",
        ngayNhap: "11/10/2024",
        nguoiNhap: "Lê Văn K",
        nhaCungCap: "Công ty DEF",
        trangThai: "Đã hoàn thành",
        tongTien: "850,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Giấy A4",
                soLuong: 10,
                giaNhap: 85000,
                thanhTien: 850000,
            },
        ],
    },
    {
        maPhieu: "PN012",
        ngayNhap: "12/10/2024",
        nguoiNhap: "Trần Văn L",
        nhaCungCap: "Công ty ABC",
        trangThai: "Đã hoàn thành",
        tongTien: "950,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Mực in Canon",
                soLuong: 10,
                giaNhap: 95000,
                thanhTien: 950000,
            },
        ],
    },
    {
        maPhieu: "PN013",
        ngayNhap: "13/10/2024",
        nguoiNhap: "Nguyễn Thị M",
        nhaCungCap: "Công ty XYZ",
        trangThai: "Đang xử lý",
        tongTien: "720,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Kẹp file",
                soLuong: 200,
                giaNhap: 3600,
                thanhTien: 720000,
            },
        ],
    },
    {
        maPhieu: "PN014",
        ngayNhap: "14/10/2024",
        nguoiNhap: "Lê Văn N",
        nhaCungCap: "Công ty DEF",
        trangThai: "Đã hoàn thành",
        tongTien: "1,500,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Máy quét mã vạch",
                soLuong: 3,
                giaNhap: 500000,
                thanhTien: 1500000,
            },
        ],
    },
    {
        maPhieu: "PN015",
        ngayNhap: "15/10/2024",
        nguoiNhap: "Phạm Thị O",
        nhaCungCap: "Công ty GHI",
        trangThai: "Đã hoàn thành",
        tongTien: "800,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Chuột không dây",
                soLuong: 20,
                giaNhap: 40000,
                thanhTien: 800000,
            },
        ],
    },
    {
        maPhieu: "PN016",
        ngayNhap: "16/10/2024",
        nguoiNhap: "Nguyễn Văn P",
        nhaCungCap: "Công ty JKL",
        trangThai: "Đang xử lý",
        tongTien: "350,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Dây cáp USB",
                soLuong: 50,
                giaNhap: 7000,
                thanhTien: 350000,
            },
        ],
    },
    {
        maPhieu: "PN017",
        ngayNhap: "17/10/2024",
        nguoiNhap: "Trần Thị Q",
        nhaCungCap: "Công ty MNO",
        trangThai: "Đã hoàn thành",
        tongTien: "400,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bàn phím cơ",
                soLuong: 2,
                giaNhap: 200000,
                thanhTien: 400000,
            },
        ],
    },
    {
        maPhieu: "PN018",
        ngayNhap: "18/10/2024",
        nguoiNhap: "Lê Văn R",
        nhaCungCap: "Công ty PQR",
        trangThai: "Đã hoàn thành",
        tongTien: "600,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Tai nghe Bluetooth",
                soLuong: 6,
                giaNhap: 100000,
                thanhTien: 600000,
            },
        ],
    },
    {
        maPhieu: "PN019",
        ngayNhap: "19/10/2024",
        nguoiNhap: "Phạm Thị S",
        nhaCungCap: "Công ty STU",
        trangThai: "Đang xử lý",
        tongTien: "500,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Ổ cứng di động",
                soLuong: 5,
                giaNhap: 100000,
                thanhTien: 500000,
            },
        ],
    },
    {
        maPhieu: "PN020",
        ngayNhap: "20/10/2024",
        nguoiNhap: "Nguyễn Văn T",
        nhaCungCap: "Công ty VWX",
        trangThai: "Đã hoàn thành",
        tongTien: "450,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Thẻ nhớ 32GB",
                soLuong: 15,
                giaNhap: 30000,
                thanhTien: 450000,
            },
        ],
    },
    {
        maPhieu: "PN021",
        ngayNhap: "21/10/2024",
        nguoiNhap: "Trần Thị U",
        nhaCungCap: "Công ty YZA",
        trangThai: "Đã hoàn thành",
        tongTien: "400,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Cục sạc dự phòng",
                soLuong: 2,
                giaNhap: 200000,
                thanhTien: 400000,
            },
        ],
    },
    {
        maPhieu: "PN022",
        ngayNhap: "22/10/2024",
        nguoiNhap: "Lê Văn V",
        nhaCungCap: "Công ty ABC",
        trangThai: "Đã hoàn thành",
        tongTien: "300,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Giấy A3",
                soLuong: 15,
                giaNhap: 20000,
                thanhTien: 300000,
            },
        ],
    },
    {
        maPhieu: "PN023",
        ngayNhap: "23/10/2024",
        nguoiNhap: "Phạm Thị W",
        nhaCungCap: "Công ty XYZ",
        trangThai: "Đang xử lý",
        tongTien: "550,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bút bi màu",
                soLuong: 110,
                giaNhap: 5000,
                thanhTien: 550000,
            },
        ],
    },
    {
        maPhieu: "PN024",
        ngayNhap: "24/10/2024",
        nguoiNhap: "Nguyễn Văn X",
        nhaCungCap: "Công ty DEF",
        trangThai: "Đã hoàn thành",
        tongTien: "250,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Sạc nhanh USB",
                soLuong: 10,
                giaNhap: 25000,
                thanhTien: 250000,
            },
        ],
    },
    {
        maPhieu: "PN025",
        ngayNhap: "25/10/2024",
        nguoiNhap: "Trần Thị Y",
        nhaCungCap: "Công ty GHI",
        trangThai: "Đang xử lý",
        tongTien: "800,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Đèn LED",
                soLuong: 8,
                giaNhap: 100000,
                thanhTien: 800000,
            },
        ],
    },
    {
        maPhieu: "PN026",
        ngayNhap: "26/10/2024",
        nguoiNhap: "Lê Văn Z",
        nhaCungCap: "Công ty JKL",
        trangThai: "Đã hoàn thành",
        tongTien: "1,200,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Máy chiếu mini",
                soLuong: 2,
                giaNhap: 600000,
                thanhTien: 1200000,
            },
        ],
    },
    {
        maPhieu: "PN027",
        ngayNhap: "27/10/2024",
        nguoiNhap: "Nguyễn Thị AA",
        nhaCungCap: "Công ty MNO",
        trangThai: "Đang xử lý",
        tongTien: "150,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Kẹp tài liệu",
                soLuong: 30,
                giaNhap: 5000,
                thanhTien: 150000,
            },
        ],
    },
    {
        maPhieu: "PN028",
        ngayNhap: "28/10/2024",
        nguoiNhap: "Phạm Văn BB",
        nhaCungCap: "Công ty PQR",
        trangThai: "Đã hoàn thành",
        tongTien: "350,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Bút chì",
                soLuong: 70,
                giaNhap: 5000,
                thanhTien: 350000,
            },
        ],
    },
    {
        maPhieu: "PN029",
        ngayNhap: "29/10/2024",
        nguoiNhap: "Trần Thị CC",
        nhaCungCap: "Công ty STU",
        trangThai: "Đã hoàn thành",
        tongTien: "500,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Giấy dán tường",
                soLuong: 10,
                giaNhap: 50000,
                thanhTien: 500000,
            },
        ],
    },
    {
        maPhieu: "PN030",
        ngayNhap: "30/10/2024",
        nguoiNhap: "Nguyễn Văn DD",
        nhaCungCap: "Công ty VWX",
        trangThai: "Đang xử lý",
        tongTien: "650,000 VND",
        chiTietPhieuNhap: [
            {
                tenHangHoa: "Túi chống sốc laptop",
                soLuong: 10,
                giaNhap: 65000,
                thanhTien: 650000,
            },
        ],
    },
];
export default phieuNhapData;
