export const APP_ROUTER = {
    INDEX: "/",
    //
    HOME: "/home",
    COMPONENT: "/component",
    USER: "/user",
    ORDER: "/order",
    PRODUCT: "/product",
    ADD_PRODUCT: "/product/add-product",
    CHAT: "/chat",
    USER: "/user",
    VOUCHER: "/voucher",
    CREATEVOUCHER: "/create-voucher",
    LISTPRODUCT: "/list-product",
    LISTORDER: "/list-order",
    CATEGORY: "/categorys",
    PRODUCTDETAIL: `/product/:id`,
    ADD_PRODUCT: "/product-add",
    LIST_PROVIDER: "/providers",
    LIST_STORES: "/stores",
    STORE_RECEIPT: "/store-receipt",
    LIST_CATEGORY: "/category",
    REPORT_CATEGORY: "/report-category",
    WAREHOUSE_PRODUCT: "/warehouse-product",
    LIST_EMPLOYEE: "/employee",
    REPORTS: "/reports",
    AUTH: "auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    CHANGE_PASSWORD: "change-password",
    REFRESH_TOKEN: "/auth/accessToken-generate",
};
