const data = [
    {
        maPhieu: "DH001",
        ngayBan: "01/10/2024",
        nhanVien: "Nguyễn Văn A",
        khachHang: "Công ty ABC",
        trangThai: "Đang chờ xác nhận",
        tongTien: "1,650,000 VND",
        sanPham: [
            {
                ten: "Bàn Là Hơi Nước",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "1,000,000",
                giamgia: "10%",
                thanhTien: "900,000",
            },
            {
                ten: "Túi Đựng Quần Áo",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "300,000",
                giamgia: "0%",
                thanhTien: "300,000",
            },
            {
                ten: "Chổi Lau Nhà",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "150,000",
                giamgia: "0%",
                thanhTien: "150,000",
            },
            {
                ten: "Khăn Tắm",
                mauSac: "Trắng",
                size: "",
                soLuong: "2",
                donGia: "150,000",
                giamgia: "0%",
                thanhTien: "300,000",
            },
        ],
    },
    {
        maPhieu: "DH002",
        ngayBan: "02/10/2024",
        nhanVien: "Trần Văn B",
        khachHang: "Công ty XYZ",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "1,350,000 VND",
        sanPham: [
            {
                ten: "Máy Pha Cà Phê",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "800,000",
                giamgia: "10%",
                thanhTien: "720,000",
            },
            {
                ten: "Cốc Thủy Tinh",
                mauSac: "Trong",
                size: "",
                soLuong: "1",
                donGia: "180,000",
                giamgia: "0%",
                thanhTien: "180,000",
            },
            {
                ten: "Ấm Đun Nước",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "450,000",
                giamgia: "0%",
                thanhTien: "450,000",
            },
        ],
    },
    {
        maPhieu: "DH003",
        ngayBan: "03/10/2024",
        nhanVien: "Lê Thị C",
        khachHang: "Công ty DEF",
        trangThai: "Đang giao hàng",
        tongTien: "1,050,000 VND",
        sanPham: [
            {
                ten: "Nồi Cơm Điện",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "800,000",
                giamgia: "10%",
                thanhTien: "720,000",
            },
            {
                ten: "Chảo Chống Dính",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "250,000",
                giamgia: "0%",
                thanhTien: "250,000",
            },
            {
                ten: "Muỗng Inox",
                mauSac: "Bạc",
                size: "",
                soLuong: "2",
                donGia: "40,000",
                giamgia: "0%",
                thanhTien: "80,000",
            },
        ],
    },
    {
        maPhieu: "DH004",
        ngayBan: "04/10/2024",
        nhanVien: "Nguyễn Văn D",
        khachHang: "Công ty GHI",
        trangThai: "Đã giao",
        tongTien: "2,500,000 VND",
        sanPham: [
            {
                ten: "Bếp Gas",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "0%",
                thanhTien: "1,500,000",
            },
            {
                ten: "Dao Phay",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "200,000",
                giamgia: "10%",
                thanhTien: "180,000",
            },
            {
                ten: "Nồi Áp Suất",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "800,000",
                giamgia: "0%",
                thanhTien: "800,000",
            },
        ],
    },
    {
        maPhieu: "DH005",
        ngayBan: "05/10/2024",
        nhanVien: "Trần Thị E",
        khachHang: "Công ty JKL",
        trangThai: "Đang chờ xác nhận",
        tongTien: "1,780,000 VND",
        sanPham: [
            {
                ten: "Máy Hút Bụi",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Chổi Quét",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "200,000",
                giamgia: "0%",
                thanhTien: "200,000",
            },
            {
                ten: "Thùng Rác",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "150,000",
                giamgia: "0%",
                thanhTien: "150,000",
            },
            {
                ten: "Găng Tay",
                mauSac: "Trắng",
                size: "",
                soLuong: "2",
                donGia: "40,000",
                giamgia: "0%",
                thanhTien: "80,000",
            },
        ],
    },
    {
        maPhieu: "DH006",
        ngayBan: "06/10/2024",
        nhanVien: "Phạm Văn F",
        khachHang: "Công ty LMN",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "2,100,000 VND",
        sanPham: [
            {
                ten: "Bếp Từ",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "1,800,000",
                giamgia: "10%",
                thanhTien: "1,620,000",
            },
            {
                ten: "Nồi Hấp",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "500,000",
                giamgia: "0%",
                thanhTien: "500,000",
            },
        ],
    },
    {
        maPhieu: "DH007",
        ngayBan: "07/10/2024",
        nhanVien: "Đỗ Văn G",
        khachHang: "Công ty OPQ",
        trangThai: "Đang giao hàng",
        tongTien: "2,800,000 VND",
        sanPham: [
            {
                ten: "Máy Rửa Bát",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "2,500,000",
                giamgia: "10%",
                thanhTien: "2,250,000",
            },
            {
                ten: "Dao Gọt Hoa Quả",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "250,000",
                giamgia: "0%",
                thanhTien: "250,000",
            },
            {
                ten: "Khay Đựng Chén",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "300,000",
                giamgia: "0%",
                thanhTien: "300,000",
            },
        ],
    },
    {
        maPhieu: "DH008",
        ngayBan: "08/10/2024",
        nhanVien: "Lê Văn H",
        khachHang: "Công ty RST",
        trangThai: "Đã giao",
        tongTien: "1,500,000 VND",
        sanPham: [
            {
                ten: "Nồi Cơm Điện",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Chảo Lớn",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "420,000",
                giamgia: "0%",
                thanhTien: "420,000",
            },
        ],
    },
    {
        maPhieu: "DH009",
        ngayBan: "09/10/2024",
        nhanVien: "Phan Thị I",
        khachHang: "Công ty UVW",
        trangThai: "Đang chờ xác nhận",
        tongTien: "1,450,000 VND",
        sanPham: [
            {
                ten: "Máy Xay Sinh Tố",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,000,000",
                giamgia: "10%",
                thanhTien: "900,000",
            },
            {
                ten: "Thớt Gỗ",
                mauSac: "Nâu",
                size: "",
                soLuong: "1",
                donGia: "200,000",
                giamgia: "0%",
                thanhTien: "200,000",
            },
            {
                ten: "Nồi Hầm",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "350,000",
                giamgia: "0%",
                thanhTien: "350,000",
            },
        ],
    },
    {
        maPhieu: "DH010",
        ngayBan: "10/10/2024",
        nhanVien: "Nguyễn Văn J",
        khachHang: "Công ty ABCD",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "1,600,000 VND",
        sanPham: [
            {
                ten: "Bếp Gas Mini",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Bình Đun Siêu Tốc",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "350,000",
                giamgia: "0%",
                thanhTien: "350,000",
            },
            {
                ten: "Dao Thái",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "170,000",
                giamgia: "0%",
                thanhTien: "170,000",
            },
        ],
    },
    {
        maPhieu: "DH011",
        ngayBan: "11/10/2024",
        nhanVien: "Trần Thị K",
        khachHang: "Công ty EFGH",
        trangThai: "Đang giao hàng",
        tongTien: "2,150,000 VND",
        sanPham: [
            {
                ten: "Máy Hút Mùi",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "1,800,000",
                giamgia: "10%",
                thanhTien: "1,620,000",
            },
            {
                ten: "Bộ Nồi",
                mauSac: "Inox",
                size: "",
                soLuong: "1",
                donGia: "500,000",
                giamgia: "0%",
                thanhTien: "500,000",
            },
        ],
    },
    {
        maPhieu: "DH012",
        ngayBan: "12/10/2024",
        nhanVien: "Lê Văn L",
        khachHang: "Công ty IJKL",
        trangThai: "Đã giao",
        tongTien: "2,500,000 VND",
        sanPham: [
            {
                ten: "Bếp Từ Đôi",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "2,000,000",
                giamgia: "10%",
                thanhTien: "1,800,000",
            },
            {
                ten: "Nồi Chiên Không Dầu",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "500,000",
                giamgia: "0%",
                thanhTien: "500,000",
            },
            {
                ten: "Muỗng Nhựa",
                mauSac: "Xanh",
                size: "",
                soLuong: "5",
                donGia: "40,000",
                giamgia: "0%",
                thanhTien: "200,000",
            },
        ],
    },
    {
        maPhieu: "DH013",
        ngayBan: "13/10/2024",
        nhanVien: "Phan Văn M",
        khachHang: "Công ty MNOP",
        trangThai: "Đang chờ xác nhận",
        tongTien: "2,100,000 VND",
        sanPham: [
            {
                ten: "Máy Lọc Nước",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Chảo Rán",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "450,000",
                giamgia: "0%",
                thanhTien: "450,000",
            },
            {
                ten: "Nồi Inox",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "300,000",
                giamgia: "0%",
                thanhTien: "300,000",
            },
        ],
    },
    {
        maPhieu: "DH014",
        ngayBan: "14/10/2024",
        nhanVien: "Nguyễn Thị N",
        khachHang: "Công ty QRST",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "1,400,000 VND",
        sanPham: [
            {
                ten: "Nồi Cơm Cao Tần",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Thìa Gỗ",
                mauSac: "Nâu",
                size: "",
                soLuong: "1",
                donGia: "180,000",
                giamgia: "0%",
                thanhTien: "180,000",
            },
            {
                ten: "Chén Sứ",
                mauSac: "Trắng",
                size: "",
                soLuong: "2",
                donGia: "70,000",
                giamgia: "0%",
                thanhTien: "140,000",
            },
        ],
    },
    {
        maPhieu: "DH015",
        ngayBan: "15/10/2024",
        nhanVien: "Lê Văn O",
        khachHang: "Công ty UVWX",
        trangThai: "Đang giao hàng",
        tongTien: "2,300,000 VND",
        sanPham: [
            {
                ten: "Máy Xay Sinh Tố",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "1,000,000",
                giamgia: "10%",
                thanhTien: "900,000",
            },
            {
                ten: "Dao Gọt",
                mauSac: "Bạc",
                size: "",
                soLuong: "2",
                donGia: "300,000",
                giamgia: "0%",
                thanhTien: "300,000",
            },
            {
                ten: "Nồi Lẩu Điện",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "1,100,000",
                giamgia: "0%",
                thanhTien: "1,100,000",
            },
        ],
    },
    {
        maPhieu: "DH016",
        ngayBan: "16/10/2024",
        nhanVien: "Trần Thị P",
        khachHang: "Công ty YZAB",
        trangThai: "Đã giao",
        tongTien: "2,750,000 VND",
        sanPham: [
            {
                ten: "Bếp Điện",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "2,000,000",
                giamgia: "10%",
                thanhTien: "1,800,000",
            },
            {
                ten: "Lò Vi Sóng",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "750,000",
                giamgia: "0%",
                thanhTien: "750,000",
            },
            {
                ten: "Bộ Bát Đĩa",
                mauSac: "Trắng",
                size: "",
                soLuong: "2",
                donGia: "100,000",
                giamgia: "0%",
                thanhTien: "200,000",
            },
        ],
    },
    {
        maPhieu: "DH017",
        ngayBan: "17/10/2024",
        nhanVien: "Nguyễn Văn Q",
        khachHang: "Công ty BCDE",
        trangThai: "Đang chờ xác nhận",
        tongTien: "1,650,000 VND",
        sanPham: [
            {
                ten: "Máy Nướng Bánh Mì",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Bình Giữ Nhiệt",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "350,000",
                giamgia: "0%",
                thanhTien: "350,000",
            },
            {
                ten: "Thớt Nhựa",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "220,000",
                giamgia: "0%",
                thanhTien: "220,000",
            },
        ],
    },
    {
        maPhieu: "DH018",
        ngayBan: "18/10/2024",
        nhanVien: "Lê Văn R",
        khachHang: "Công ty CDEF",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "2,200,000 VND",
        sanPham: [
            {
                ten: "Máy Vắt Cam",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Chảo Xào",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "450,000",
                giamgia: "0%",
                thanhTien: "450,000",
            },
            {
                ten: "Bộ Đĩa",
                mauSac: "Trắng",
                size: "",
                soLuong: "3",
                donGia: "70,000",
                giamgia: "0%",
                thanhTien: "210,000",
            },
        ],
    },
    {
        maPhieu: "DH019",
        ngayBan: "19/10/2024",
        nhanVien: "Trần Thị S",
        khachHang: "Công ty GHIJ",
        trangThai: "Đang giao hàng",
        tongTien: "2,600,000 VND",
        sanPham: [
            {
                ten: "Máy Hút Bụi",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "2,000,000",
                giamgia: "10%",
                thanhTien: "1,800,000",
            },
            {
                ten: "Lò Nướng",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "800,000",
                giamgia: "0%",
                thanhTien: "800,000",
            },
        ],
    },
    {
        maPhieu: "DH020",
        ngayBan: "20/10/2024",
        nhanVien: "Nguyễn Văn T",
        khachHang: "Công ty JKLM",
        trangThai: "Đã giao",
        tongTien: "1,850,000 VND",
        sanPham: [
            {
                ten: "Máy Rửa Chén",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Bàn Ủi",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "500,000",
                giamgia: "0%",
                thanhTien: "500,000",
            },
        ],
    },
    {
        maPhieu: "DH021",
        ngayBan: "21/10/2024",
        nhanVien: "Nguyễn Thị A",
        khachHang: "Công ty NOPQ",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "1,900,000 VND",
        sanPham: [
            {
                ten: "Bếp Ga Âm",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Nồi Áp Suất",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "400,000",
                giamgia: "0%",
                thanhTien: "400,000",
            },
            {
                ten: "Chén Nhựa",
                mauSac: "Xanh",
                size: "",
                soLuong: "2",
                donGia: "75,000",
                giamgia: "0%",
                thanhTien: "150,000",
            },
        ],
    },
    {
        maPhieu: "DH022",
        ngayBan: "22/10/2024",
        nhanVien: "Trần Văn B",
        khachHang: "Công ty QRST",
        trangThai: "Đang giao hàng",
        tongTien: "2,450,000 VND",
        sanPham: [
            {
                ten: "Máy Xay Đa Năng",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "1,700,000",
                giamgia: "10%",
                thanhTien: "1,530,000",
            },
            {
                ten: "Bình Đun Siêu Tốc",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "500,000",
                giamgia: "0%",
                thanhTien: "500,000",
            },
            {
                ten: "Bàn Chải Điện",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "420,000",
                giamgia: "0%",
                thanhTien: "420,000",
            },
        ],
    },
    {
        maPhieu: "DH023",
        ngayBan: "23/10/2024",
        nhanVien: "Lê Thị C",
        khachHang: "Công ty UVWX",
        trangThai: "Đã giao",
        tongTien: "1,850,000 VND",
        sanPham: [
            {
                ten: "Bếp Hồng Ngoại",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "1,300,000",
                giamgia: "10%",
                thanhTien: "1,170,000",
            },
            {
                ten: "Dao Kéo Bộ",
                mauSac: "Inox",
                size: "",
                soLuong: "1",
                donGia: "550,000",
                giamgia: "0%",
                thanhTien: "550,000",
            },
        ],
    },
    {
        maPhieu: "DH024",
        ngayBan: "24/10/2024",
        nhanVien: "Phạm Văn D",
        khachHang: "Công ty YZAB",
        trangThai: "Đang chờ xác nhận",
        tongTien: "1,600,000 VND",
        sanPham: [
            {
                ten: "Máy Lọc Không Khí",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Nồi Cơm Điện",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "520,000",
                giamgia: "0%",
                thanhTien: "520,000",
            },
        ],
    },
    {
        maPhieu: "DH025",
        ngayBan: "25/10/2024",
        nhanVien: "Nguyễn Thị E",
        khachHang: "Công ty CDEF",
        trangThai: "Đang giao hàng",
        tongTien: "2,000,000 VND",
        sanPham: [
            {
                ten: "Bộ Đồ Dùng Nhà Bếp",
                mauSac: "Xanh",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Đèn Ngủ",
                mauSac: "Trắng",
                size: "",
                soLuong: "2",
                donGia: "325,000",
                giamgia: "0%",
                thanhTien: "650,000",
            },
        ],
    },
    {
        maPhieu: "DH026",
        ngayBan: "26/10/2024",
        nhanVien: "Trần Văn F",
        khachHang: "Công ty GHIJ",
        trangThai: "Đang chờ vận chuyển",
        tongTien: "1,900,000 VND",
        sanPham: [
            {
                ten: "Nồi Lẩu",
                mauSac: "Bạc",
                size: "",
                soLuong: "1",
                donGia: "1,400,000",
                giamgia: "10%",
                thanhTien: "1,260,000",
            },
            {
                ten: "Thìa Gỗ",
                mauSac: "Nâu",
                size: "",
                soLuong: "2",
                donGia: "320,000",
                giamgia: "0%",
                thanhTien: "320,000",
            },
            {
                ten: "Tô Sứ",
                mauSac: "Trắng",
                size: "",
                soLuong: "3",
                donGia: "120,000",
                giamgia: "0%",
                thanhTien: "360,000",
            },
        ],
    },
    {
        maPhieu: "DH027",
        ngayBan: "27/10/2024",
        nhanVien: "Lê Thị G",
        khachHang: "Công ty JKLM",
        trangThai: "Đã giao",
        tongTien: "2,300,000 VND",
        sanPham: [
            {
                ten: "Máy Xay Thịt",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "1,800,000",
                giamgia: "10%",
                thanhTien: "1,620,000",
            },
            {
                ten: "Đèn Pin",
                mauSac: "Đỏ",
                size: "",
                soLuong: "1",
                donGia: "700,000",
                giamgia: "0%",
                thanhTien: "700,000",
            },
        ],
    },
    {
        maPhieu: "DH028",
        ngayBan: "28/10/2024",
        nhanVien: "Nguyễn Văn H",
        khachHang: "Công ty MNOP",
        trangThai: "Đang chờ xác nhận",
        tongTien: "2,100,000 VND",
        sanPham: [
            {
                ten: "Nồi Chiên Không Dầu",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Đèn Trang Trí",
                mauSac: "Vàng",
                size: "",
                soLuong: "2",
                donGia: "375,000",
                giamgia: "0%",
                thanhTien: "750,000",
            },
        ],
    },
    {
        maPhieu: "DH029",
        ngayBan: "29/10/2024",
        nhanVien: "Trần Thị I",
        khachHang: "Công ty UVWX",
        trangThai: "Đang giao hàng",
        tongTien: "1,750,000 VND",
        sanPham: [
            {
                ten: "Máy Pha Cà Phê",
                mauSac: "Xám",
                size: "",
                soLuong: "1",
                donGia: "1,200,000",
                giamgia: "10%",
                thanhTien: "1,080,000",
            },
            {
                ten: "Máy Xay Cà Phê",
                mauSac: "Đen",
                size: "",
                soLuong: "1",
                donGia: "670,000",
                giamgia: "0%",
                thanhTien: "670,000",
            },
        ],
    },
    {
        maPhieu: "DH030",
        ngayBan: "30/10/2024",
        nhanVien: "Phạm Văn J",
        khachHang: "Công ty YZAB",
        trangThai: "Đã giao",
        tongTien: "1,900,000 VND",
        sanPham: [
            {
                ten: "Máy Rửa Mặt",
                mauSac: "Hồng",
                size: "",
                soLuong: "1",
                donGia: "1,500,000",
                giamgia: "10%",
                thanhTien: "1,350,000",
            },
            {
                ten: "Gương Trang Điểm",
                mauSac: "Trắng",
                size: "",
                soLuong: "1",
                donGia: "550,000",
                giamgia: "0%",
                thanhTien: "550,000",
            },
        ],
    },
];
export default data;
